name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # preserve tags
          fetch-depth: 0
      - name: Install
        run: yarn install
      - name: Install Web
        run: cd web && yarn install
      - name: Build
        run: yarn build
      - name: Package
        run: cd out && zip weaselthief.zip -r . && mv weaselthief.zip ..
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: weaselthief.zip
 